### PR TITLE
Prevents blank 303, and correctly adds file to canvas

### PR DESCRIPTION
**Pull request by Cory-Christensen**
The do block was returning a blank 303 and not posting the file to canvas. This small change added the file correctly and returned the appropriate response.

### CODE REVIEW

**Comment by bfcoder** [comment]
This doesn't work. The rest client does not work like this. You have to handle a redirect in a block. https://github.com/rest-client/rest-client#exceptions-see-httpwwww3orgprotocolsrfc2616rfc2616-sec10html

**Comment by Cory-Christensen** [comment]
RestClient automatically follows 302 redirects - you don't have to handle it at all

"for result codes 301, 302 or 307, the redirection will be followed if the request is a GET or a HEAD"

**Comment by bfcoder** [comment]
If you say so and it has been thoroughly tested. I just know the reason I put it into a block was because rest-client was being retarded and would throw an error on the redirect and it had to be rescued.

**Comment by Cory-Christensen** [comment]
Feel free to test it for sure. It worked great for mr

**Comment by bfcoder** [comment]
I get an error:
```
Completed 500 Internal Server Error in 16252ms (ActiveRecord: 5.6ms)

RestClient::Found (302 Found):
  app/controllers/api/scorm_courses_controller.rb:132:in `upload_canvas_file'
  app/controllers/api/scorm_courses_controller.rb:37:in `create'
  lib/middleware/oauth_state_middleware.rb:22:in `call'
```
:/

**Comment by Cory-Christensen** [comment]
We've got a better way, deleting.

**Pull request closed without merging**
