### PR TITLE
Change Some ID Columns to bigint/8 Byte Integers

### PR DESCRIPTION
**Pull request by conradbeach**
Addresses Pivotal Tracker story [#150728671](https://www.pivotaltracker.com/story/show/150728671).

I was pretty liberal with changing columns. If it seemed conceivable that the table could have billions of records some day, I went ahead and changed the ID to `bigint`. Rails 5.1 actually defaults ID columns to `bigint`, so I felt like it made sense to err on the side of caution and make too many changes instead of too few.

That said, I'm unfamiliar with the use case for a number of the tables in the DB. Any suggestions for additions or removals to the list of columns that get changed to `bigint` is appreciated.

If there were any columns on other tables for which the changed ID columns acted as foreign keys, I changed those foreign key columns to `bigint` as well.

### CODE REVIEW

**Comment by bfcoder** [comment]
I want to wait on this until my upstream is merged in and rails 5 is in master

**Comment by bfcoder** [comment]
with the new code, it will use actual bigint fields instead of an integer with limit 8

**Comment by bfcoder** [comment]
And I don't think it necessary to change the id fields. Especially if rails 5.1 is going to do it automatically.

**Comment by conradbeach** [comment]
@bfcoder Ok. That makes sense to wait on this until upstream is merged in.

While Rails 5.1 defaults _new_ ID columns to `bigint`, I'm pretty confident it won't change the type of existing ID columns. Our existing IDs will remain 32 bit integers unless we manually change them to 64 bit.

If you still feel it's unnecessary to change ID fields to `bigint`, should we close Pivotal [#150728671](https://www.pivotaltracker.com/story/show/150728671)?

**Comment by bfcoder** [comment]
I just don't want to have any conflicts with the id's when we go to rails 5.1 eventually. Once we go to 5.1, we can upgrade all the id's the same way that rails does to keep it consistent.

**Comment by conradbeach** [comment]
Ok

**Comment by bfcoder** [comment]
Closing in favor of doing this upstream

**Pull request closed without merging**
